name: Build and publish Docker image
on:
  push:
    branches:
      - kafka-ipc
      - redis-ipc

jobs:
  build-maven:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file ./diploma-ipc/pom.xml

  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: shvatov/ipc-test-application

      - name: Push Kafka-based image
        if: endsWith(github.ref, '/kafka-ipc')
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: shvatov/ipc-test-application:kafka

      - name: Push Redis-based image
        if: endsWith(github.ref, '/kafka-ipc')
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: shvatov/ipc-test-application:redis
