name: Build, Test and Publish to Releases page
on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean install -DskipTests=true

      - name: Build Release.txt
        run: echo ${{ github.sha }} > Release.txt

      - name: Add files to latest release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          files: |
            Release.txt
            ./*/target/*.jar
#    todo
#    push-artifact:

